// Copyright Myceland Team, All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"


namespace ML_GameplayTags
{
	// ============================ Levels ============================
	MYCELAND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Level_Menu);
	MYCELAND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Level_LevelSelectionMenu);
	MYCELAND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Level_Tuto_1);
	MYCELAND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Level_Tuto_2);
	MYCELAND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Level_Tuto_3);
	MYCELAND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Level_Tuto_4);
	MYCELAND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Level_Easy_1);
	MYCELAND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Level_Easy_2);
	MYCELAND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Level_Easy_3);
	MYCELAND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Level_Easy_4);
	MYCELAND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Level_Middle_1);
	MYCELAND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Level_Middle_2);
	MYCELAND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Level_Middle_3);
	MYCELAND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Level_Hard_1);
	MYCELAND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Level_Hard_2);
	
	
	// ============================ UI ============================
	// ========== Root ==========
	MYCELAND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Root_Menu);
	MYCELAND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Root_Game);
	
	// ========== Widgets ==========
	MYCELAND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Widget_TitleScreen);
	MYCELAND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Widget_MainMenu);
	MYCELAND_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(UI_Widget_Settings);
}
