;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Content/Localization/Myceland
DestinationPath=C:/Users/Utilisateur/Downloads/Localization
NativeCulture=en
CulturesToGenerate=en
CulturesToGenerate=fr
CulturesToGenerate=ja
ManifestName=Myceland.manifest
ArchiveName=Myceland.archive
PortableObjectName=Myceland.po

[GatherTextStep0]
CommandletClass=InternationalizationExport
bExportLoc=true
LocalizedTextCollapseMode=ELocalizedTextCollapseMode::IdenticalTextIdAndSource
POFormat=EPortableObjectFormat::Unreal
ShouldPersistCommentsOnExport=false
ShouldAddSourceLocationsAsComments=true

