;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Content/Localization/Myceland
DestinationPath=Content/Localization/Myceland
ManifestName=Myceland.manifest
ArchiveName=Myceland.archive
ResourceName=Myceland.locres
bSkipSourceCheck=false
bValidateFormatPatterns=true
bValidateSafeWhitespace=false
bValidateRichTextTags=false
NativeCulture=en
CulturesToGenerate=en
CulturesToGenerate=fr

[GatherTextStep0]
CommandletClass=GenerateTextLocalizationResource

