;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Level.World.1.Level.2.Hub",NewTagName="Puzzle.World1.Level2.Hub")
+GameplayTagRedirects=(OldTagName="Level.World.1.Level.2.Puzzle.1",NewTagName="Puzzle.World1.Level2.1")
+GameplayTagRedirects=(OldTagName="Level.World.1.Level.2.Puzzle.2",NewTagName="Puzzle.World1.Level2.2")
+GameplayTagRedirects=(OldTagName="Level.World.1.Level.2.Puzzle.3",NewTagName="Puzzle.World1.Level2.3")
+GameplayTagRedirects=(OldTagName="Level.World.1.Level.2.Puzzle.4",NewTagName="Puzzle.World1.Level2.4")
+GameplayTagRedirects=(OldTagName="Level.World.1.Level.2.Puzzle.5",NewTagName="Puzzle.World1.Level2.5")
+GameplayTagRedirects=(OldTagName="Level.World.1.Level.1.Puzzle.3",NewTagName="Puzzle.World1.Level.3")
+GameplayTagRedirects=(OldTagName="Level.World.1.Level.1.Puzzle.2",NewTagName="Puzzle.World1.Level1.2")
+GameplayTagRedirects=(OldTagName="Puzzle.World1.Level.3",NewTagName="Puzzle.World1.Level1.3")
+GameplayTagRedirects=(OldTagName="Level.World.1.Level.1.Puzzle.1",NewTagName="Puzzle.World1.Level1.1")
+GameplayTagRedirects=(OldTagName="Level.World.1.Level.1.Hub",NewTagName="Puzzle.World1.Level1.Hub")
+GameplayTagRedirects=(OldTagName="Level.World.1.Level.0.Puzzle.1",NewTagName="Puzzle.World1.Level0.1")
+GameplayTagList=(Tag="Puzzle.World1.Level0.1",DevComment="")
+GameplayTagList=(Tag="Puzzle.World1.Level1.1",DevComment="")
+GameplayTagList=(Tag="Puzzle.World1.Level1.2",DevComment="")
+GameplayTagList=(Tag="Puzzle.World1.Level1.3",DevComment="")
+GameplayTagList=(Tag="Puzzle.World1.Level1.Hub",DevComment="")
+GameplayTagList=(Tag="Puzzle.World1.Level2.1",DevComment="")
+GameplayTagList=(Tag="Puzzle.World1.Level2.2",DevComment="")
+GameplayTagList=(Tag="Puzzle.World1.Level2.3",DevComment="")
+GameplayTagList=(Tag="Puzzle.World1.Level2.4",DevComment="")
+GameplayTagList=(Tag="Puzzle.World1.Level2.5",DevComment="")
+GameplayTagList=(Tag="Puzzle.World1.Level2.Hub",DevComment="")

